name: Dev Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup
      run: sudo apt-get install -y gcc-mingw-w64
      
    - name: Make
      run: make 'CONF=win32'

    - name: Set tag name
      id: tag
      run: |
        echo "tag=$(basename ${{ github.ref }})" >> $GITHUB_OUTPUT
        
    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        tag="${{ steps.tag.outputs.tag }}"; gh release create --draft "$tag" --title "$tag"
        
    - name: Upload
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release upload "${{ steps.tag.outputs.tag }}" drawterm.exe

    - name: Publish Release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release edit "${{ needs.release.outputs.tag }}" --draft=false
